# gem 'pg' 
# 
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: melius
  password: melius
  pool: 5
  
development:
  <<: *default
  database: task_api_development

master:
  <<: *default
  database: task_api_development

test:
  <<: *default
  database: task_api_test
 
